### ISSUE TITLE
Unsupported path

### ISSUE THREAD

**Issue by grylem** [jemtucker/trash#2]
Hi.
file with name started witch dot
trash .test
trash[14390:2242108] ERROR Unsupported path
Please fix it.

**Comment by jemtucker** [comment]
@grylem can you test that branch please

**Comment by grylem** [comment]
Now can trash but "trash -l" dont show files with name started witch dot in .Trash
Also "trash -e" not working for these files. If .Trash contains not only dot name files, file without dot
list and empty but files with dot name remain in the .Trash

**Comment by grylem** [comment]
found another strange thing with file name.
find . -type f -name "*.mp3"  -exec trash {} \;
for files with the simple name like 1.mp3 or test.mp3 is working
for file with names with space "1 test.mp3" or has cyrillic names trash terminated with message
"trash[2324:48315] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager trashItemAtURL:resultingItemURL:error:]: source URL is nil'"

**Comment by jemtucker** [comment]
Okay, I think I have fixed the issue with hidden files (had to change the build tools too as tup is no longer supported on Travis nicely). Try building again and let me know what you think.

Regarding the other issue, I have opened this in a new thread - #5

**Comment by grylem** [comment]
latest build:
trash .DS_Store
trash -l  - dont show
ls .Trash show  .DS_Store
trash other .DS_Store and now trash -l show all .DS_Store
trash -e  first trashed .DS_Store remains.
Regards.

**Comment by jemtucker** [comment]
Running this myself I see the following behaviour...

```
$ touch .DS_Store
$ ls -a
.           ..          .DS_Store
$ trash .DS_Store
$ trash -l
.DS_Store 15-20-29-921
```

The .DS_Store 15-20-29-921 is the DS_Store file, it has been given a timestamp because a .DS_Store file already exists in the ~/.Trash directory (this is where macOS stores metadata regarding the trash). By running `trash --put-back` on this file, the local .DS_Store is replaced.

```
$ trash -p ".DS_Store 15-20-29-921"
$ ls -a
.           ..          .DS_Store
```

This is expected behaviour due to how the macOS functions.
